- id: 1
  key: dollar
  code: usd
  symbol: "$"
  coin: false
  precision: 2
  inuse: true
  assets:
    accounts:
      - bank: "Demo Bank"
        address: "6225 0885 6022 3501"
        password: "111111"
        tel: "95555"
- id: 2
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 10
  inuse: true
  rpc: http://root:123456@127.0.0.1:19332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      - address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3
- id: 3
  key: ripple
  code: xrp
  symbol: "ꭆ"
  coin: true
  quick_withdraw_max: 110
  rpc: "https://s1.ripple.com:51233"
  blockchain: "https://bithomp.com/explorer/#{txid}"
  address_url: "https://bithomp.com/explorer/#{address}"
  assets:
    accounts:
      - address: rfZ2qiX4WuDdvcJEG1zPtiuDKzXrr6YF7T
        secret: shD23b3pSNzgBmbiUMTs8YRQDYdoM
- id: 4
  key: litecoin
  code: ltc
  coin: true
  rpc: http://root:123456@127.0.0.1:18332
  blockchain: http://ltc.blockr.io/tx/info/#{txid}
  address_url: http://ltc.blockr.io/address/info/#{address}
  assets:
    accounts:
      - address: 0x4bA2474e063Aec44e23F2Bf7Fb9e4e2878dBaB44
- id: 5
  key: deadal
  code: bch
  coin: true
  rpc: http://khalid1190:n@meer@30@127.0.0.1:9332
  blockchain: http://ltc.blockr.io/tx/info/#{txid}
  address_url: http://ltc.blockr.io/address/info/#{address}
- id: 6
  key: dashcoin
  code: dsh
  coin: true
  rpc: http://khalid1190:n@meer@30@127.0.0.1:9332
  blockchain: http://ltc.blockr.io/tx/info/#{txid}
  address_url: http://ltc.blockr.io/address/info/#{address}
- id: 7
  key: stellar
  code: xlm
  coin: true
  rpc: http://khalid1190:n@meer@30@127.0.0.1:9332
  blockchain: http://ltc.blockr.io/tx/info/#{txid}
  address_url: http://ltc.blockr.io/address/info/#{address}
- id: 8
  key: tether
  code: usdt
  coin: true
  rpc: http://khalid1190:n@meer@30@127.0.0.1:9332
  blockchain: http://ltc.blockr.io/tx/info/#{txid}
  address_url: http://ltc.blockr.io/address/info/#{address}